# Generated by Django 4.1.2 on 2022-10-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesslocations',
            name='accessHours',
            field=models.CharField(max_length=100),
        ),
    ]
